# Generated by Django 4.1 on 2022-11-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AfternoonTea',
            new_name='Cake',
        ),
    ]
