# Generated by Django 4.1 on 2022-11-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfternoonTea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('under_review', models.BooleanField(default=True)),
                ('no_of_people', models.PositiveIntegerField(null=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tea_order', to='profiles.userprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='afternoontea',
            constraint=models.CheckConstraint(check=models.Q(('no_of_people__range', (1, 25000))), name='afternoon_tea_afternoontea_no_of_people_range'),
        ),
    ]
