# Generated by Django 4.1 on 2022-11-16 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_tea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afternoontea',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='afternoontea',
            name='date',
            field=models.DateField(),
        ),
    ]
