# Generated by Django 4.1 on 2022-11-16 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_tea', '0003_alter_afternoontea_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoontea',
            name='date',
            field=models.DateField(choices=[(datetime.date(2022, 12, 10), 'Sat'), (datetime.date(2022, 12, 11), 'Sun'), (datetime.date(2022, 12, 17), 'Sat'), (datetime.date(2022, 12, 18), 'Sun'), (datetime.date(2022, 12, 24), 'Sat'), (datetime.date(2022, 12, 25), 'Sun')]),
        ),
    ]
