# Generated by Django 4.1 on 2022-11-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_tea', '0005_alter_afternoontea_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='afternoontea',
            name='booking_number',
            field=models.CharField(default=12, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
