# Generated by Django 4.1 on 2022-11-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_tea', '0007_remove_afternoontea_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoontea',
            name='time',
            field=models.CharField(choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], max_length=6),
        ),
    ]
