# Generated by Django 4.1 on 2022-11-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_tea', '0009_remove_afternoontea_afternoon_tea_afternoontea_no_of_people_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afternoontea',
            name='user_profile',
        ),
    ]
