# Generated by Django 4.1 on 2022-12-08 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_tea', '0010_remove_afternoontea_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoontea',
            name='date',
            field=models.DateField(choices=[(datetime.date(2022, 12, 31), 'Sat: Dec 31'), (datetime.date(2023, 1, 1), 'Sun: Jan 01'), (datetime.date(2023, 1, 7), 'Sat: Jan 07'), (datetime.date(2023, 1, 8), 'Sun: Jan 08'), (datetime.date(2023, 1, 14), 'Sat: Jan 14'), (datetime.date(2023, 1, 15), 'Sun: Jan 15')]),
        ),
    ]
