# Generated by Django 4.1 on 2022-12-21 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_tea', '0011_alter_afternoontea_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoontea',
            name='date',
            field=models.DateField(choices=[(datetime.date(2023, 1, 14), 'Sat: Jan 14'), (datetime.date(2023, 1, 15), 'Sun: Jan 15'), (datetime.date(2023, 1, 21), 'Sat: Jan 21'), (datetime.date(2023, 1, 22), 'Sun: Jan 22'), (datetime.date(2023, 1, 28), 'Sat: Jan 28'), (datetime.date(2023, 1, 29), 'Sun: Jan 29')]),
        ),
    ]
