# Generated by Django 4.1 on 2022-12-12 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collection_date',
            field=models.DateField(choices=[(datetime.date(2022, 12, 13), 'Tue: Dec 13'), (datetime.date(2022, 12, 14), 'Wed: Dec 14'), (datetime.date(2022, 12, 15), 'Thu: Dec 15'), (datetime.date(2022, 12, 16), 'Fri: Dec 16'), (datetime.date(2022, 12, 17), 'Sat: Dec 17'), (datetime.date(2022, 12, 18), 'Sun: Dec 18'), (datetime.date(2022, 12, 19), 'Mon: Dec 19'), (datetime.date(2022, 12, 20), 'Tue: Dec 20')], null=True),
        ),
    ]
