# Generated by Django 4.1 on 2022-10-13 20:18

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gluten', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('nut', models.BooleanField(default=False)),
                ('soy', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('celery', models.BooleanField(default=False)),
                ('mustard', models.BooleanField(default=False)),
                ('sesame_seed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('delivery', models.BooleanField(default=False)),
                ('collection', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('ingredients', models.TextField()),
                ('allergens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.allergens')),
            ],
        ),
    ]
