# Generated by Django 4.0.6 on 2022-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.AddField(
            model_name='product',
            name='celery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='egg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='milk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mustard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='nut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sesame_seed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='soy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Allergens',
        ),
    ]
