# Generated by Django 4.0.6 on 2022-11-18 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gluten', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('nut', models.BooleanField(default=False)),
                ('soy', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('celery', models.BooleanField(default=False)),
                ('mustard', models.BooleanField(default=False)),
                ('sesame_seed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='celery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='egg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gluten',
        ),
        migrations.RemoveField(
            model_name='product',
            name='milk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mustard',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nut',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sesame_seed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='soy',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.allergens'),
        ),
    ]
