# Generated by Django 4.0.6 on 2022-11-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_allergens_remove_product_celery_remove_product_egg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergens',
            name='celery',
        ),
        migrations.RemoveField(
            model_name='allergens',
            name='egg',
        ),
        migrations.RemoveField(
            model_name='allergens',
            name='gluten',
        ),
        migrations.RemoveField(
            model_name='allergens',
            name='milk',
        ),
        migrations.RemoveField(
            model_name='allergens',
            name='mustard',
        ),
        migrations.RemoveField(
            model_name='allergens',
            name='nut',
        ),
        migrations.RemoveField(
            model_name='allergens',
            name='sesame_seed',
        ),
        migrations.RemoveField(
            model_name='allergens',
            name='soy',
        ),
        migrations.AddField(
            model_name='allergens',
            name='allergy',
            field=models.CharField(choices=[('gluten', 'gluten'), ('egg', 'egg'), ('nut', 'nut'), ('soy', 'soy'), ('milk', 'milk'), ('celery', 'celery'), ('mustard', 'mustard'), ('sesame_seed', 'sesame seed')], default='egg', max_length=11),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(to='products.allergens'),
        ),
    ]
