# Generated by Django 4.1 on 2022-11-27 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_allergens_celery_remove_allergens_egg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection_date',
            field=models.DateField(choices=[(datetime.date(2022, 11, 28), 'Mon: Nov 28'), (datetime.date(2022, 11, 29), 'Tue: Nov 29'), (datetime.date(2022, 11, 30), 'Wed: Nov 30'), (datetime.date(2022, 12, 1), 'Thu: Dec 01'), (datetime.date(2022, 12, 2), 'Fri: Dec 02'), (datetime.date(2022, 12, 3), 'Sat: Dec 03'), (datetime.date(2022, 12, 4), 'Sun: Dec 04'), (datetime.date(2022, 12, 5), 'Mon: Dec 05')], null=True),
        ),
    ]
