# Generated by Django 4.1 on 2022-11-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_collection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection_date',
        ),
    ]
