# Generated by Django 4.1 on 2022-12-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='individual_dessert',
            field=models.BooleanField(default=False),
        ),
    ]
