# Generated by Django 4.1 on 2022-12-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_individual_dessert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergens',
            name='allergy',
            field=models.CharField(choices=[('gluten', 'gluten'), ('egg', 'egg'), ('nut', 'nut'), ('soy', 'soy'), ('milk', 'milk'), ('celery', 'celery'), ('mustard', 'mustard'), ('sesame_seed', 'sesame seed'), ('wheat', 'wheat'), ('sulphites', 'sulphites'), ('gelatine', 'gelatine')], max_length=11),
        ),
    ]
