# Generated by Django 4.1 on 2022-12-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_allergens_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mince_pies',
            field=models.BooleanField(default=False),
        ),
    ]
