# Generated by Django 4.1 on 2022-12-17 21:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_mince_pies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, to='products.allergens'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
